[package]
name = "alphazero-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3.74"
bincode = "1.3.3"
burn = { version = "0.14.0", features = ["wgpu", "train", "autodiff", "fusion"] }
petgraph = "0.6.5"
rand = "0.8.5"
rayon = "1.10.0"
